# Generated by Django 6.0.4 on 2026-04-15 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('rather not say', 'Rather Not Say')], max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student/profile_images/')),
                ('bio', models.TextField(blank=True)),
                ('qualification', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('working', 'Working')], default='school', max_length=8)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('interests', models.CharField(blank=True, max_length=200)),
                ('goals', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('rather not say', 'Rather Not Say')], max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher/profile_images/')),
                ('bio', models.TextField(blank=True)),
                ('qualification', models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD')], default='bachelors', max_length=10)),
                ('expertise', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('languages', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
