# Generated by Django 6.0.4 on 2026-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='languages',
            field=models.CharField(max_length=200),
        ),
    ]
